"""Document processing pipeline modules."""
from app.pipeline.types import (
    PreprocessedPage,
    PreprocessingResult,
    BoundingBox,
    OCRBlock,
    OCRPageResult,
    OCRMetadata,
    OCRDocumentResult,
    DocumentType,
    GeminiClassificationOutput,
    DocumentClassificationResult,
    InvoiceSectionType,
    OnboardingSectionType,
    GeminiRawSection,
    GeminiSectionDetectionOutput,
    DocumentSection,
    DocumentSectionResult,
    ExtractedField,
    DocumentExtractionResult,
)
from app.pipeline.preprocessing import preprocess_document
from app.pipeline.ocr import (
    BaseOCREngine,
    TesseractOCREngine,
    OCREngineError,
    OCREngineUnavailableError,
    get_ocr_engine,
)
from app.pipeline.classifier import DocumentClassifier, classify_document
from app.pipeline.section_detector import SectionDetector, detect_sections_for_document
from app.pipeline.extractor import DocumentExtractor, extract_document_fields

__all__ = [
    "PreprocessedPage",
    "PreprocessingResult",
    "preprocess_document",
    "BoundingBox",
    "OCRBlock",
    "OCRPageResult",
    "OCRMetadata",
    "OCRDocumentResult",
    "DocumentType",
    "GeminiClassificationOutput",
    "DocumentClassificationResult",
    "InvoiceSectionType",
    "OnboardingSectionType",
    "GeminiRawSection",
    "GeminiSectionDetectionOutput",
    "DocumentSection",
    "DocumentSectionResult",
    "ExtractedField",
    "DocumentExtractionResult",
    "BaseOCREngine",
    "TesseractOCREngine",
    "OCREngineError",
    "OCREngineUnavailableError",
    "get_ocr_engine",
    "DocumentClassifier",
    "classify_document",
    "SectionDetector",
    "detect_sections_for_document",
    "DocumentExtractor",
    "extract_document_fields",
]
